spring.application.name=twitterclone
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/twitterclone}
spring.datasource.username=${DATABASE_USERNAME:twitterclone}
spring.datasource.password=${DATABASE_PASSWORD:change-me}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
