create table posts (
    id bigint generated by default as identity primary key,
    author_name varchar(255),
    author_handle varchar(255),
    content varchar(255),
    created_at timestamp(6) with time zone
);