create table users ( 
    id bigint generated by default as identity primary key,
    username varchar(30) not null unique,
    email varchar(255) not null unique, 
    password_hash varchar(255) not null, 
    display_name varchar(80) not null, 
    bio varchar(160), 
    avatar_url varchar(500), 
    role varchar(30) not null, 
    enabled boolean not null, 
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);